### ISSUE TITLE
asgiref.inmemory.ChannelFull: http.disconnect

### ISSUE THREAD

**Issue by jaywhy13** [andrewgodwin/daphne#11]
Not sure how or why I'm getting this error but I'm developing a project setup under Docker. I realized sometimes I try to load the page and my images and fonts take a while to load, then I saw this error in the console. I was developing fine before, not exactly sure what I changed. 

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/channels/management/commands/runserver.py", line 82, in inner_run
    http_timeout=60,  # Shorter timeout than normal as it's dev
  File "/usr/local/lib/python2.7/site-packages/daphne/server.py", line 49, in run
    reactor.run(installSignalHandlers=self.signal_handlers)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/local/lib/python2.7/site-packages/daphne/server.py", line 69, in backend_reader
    self.factory.dispatch_reply(channel, message)
  File "/usr/local/lib/python2.7/site-packages/daphne/http_protocol.py", line 244, in dispatch_reply
    self.reply_protocols[channel].serverResponse(message)
  File "/usr/local/lib/python2.7/site-packages/daphne/http_protocol.py", line 171, in serverResponse
    self.finish()
  File "/usr/local/lib/python2.7/site-packages/daphne/http_protocol.py", line 144, in finish
    self.send_disconnect()
  File "/usr/local/lib/python2.7/site-packages/daphne/http_protocol.py", line 126, in send_disconnect
    "reply_channel": self.reply_channel,
  File "/usr/local/lib/python2.7/site-packages/asgiref/inmemory.py", line 50, in send
    raise self.ChannelFull(channel)
```

**Comment by andrewgodwin** [comment]
Have you upgraded Daphne to the latest version? It should understand backpressure and ignore this warning (it's for the disconnect channel, which is optional for you to consume)

**Comment by jaywhy13** [comment]
Great, confirming I don't have the issue with the latest 0.13.0. Thanks!
