### ISSUE TITLE
Critical: Daphne process can be killed using unallowed characters in URL

### ISSUE THREAD

**Issue by darklow** [andrewgodwin/daphne#12]
Our site just went down few times, because apparently some bots are requesting our site with illegal unicode chars in the path. The bad part is that daphne shows an error, stops serving, but the process stays, therefore supervisorctl is not restarting a task. 
Test case:
```
daphne project.asgi:channel_layer -b 0.0.0.0 -p 8000
```
Run following curl. These three dots is a unicode character:
```
curl http://localhost:8000/…/test
```

After the request daphne shows error and stops serving, but process stays up and if you try to load url it will hang on loading and never show anything until get timed outed:
```
Unhandled Error
Traceback (most recent call last):
  File "/Users/darklow/www/30sec/env/lib/python2.7/site-packages/daphne/cli.py", line 133, in run
    ws_protocols=args.ws_protocols,
  File "/Users/darklow/www/30sec/env/lib/python2.7/site-packages/daphne/server.py", line 52, in run
    reactor.run(installSignalHandlers=self.signal_handlers)
  File "/Users/darklow/www/30sec/env/lib/python2.7/site-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/Users/darklow/www/30sec/env/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/Users/darklow/www/30sec/env/lib/python2.7/site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/Users/darklow/www/30sec/env/lib/python2.7/site-packages/daphne/server.py", line 72, in backend_reader
    self.factory.dispatch_reply(channel, message)
  File "/Users/darklow/www/30sec/env/lib/python2.7/site-packages/daphne/http_protocol.py", line 269, in dispatch_reply
    self.reply_protocols[channel].serverResponse(message)
  File "/Users/darklow/www/30sec/env/lib/python2.7/site-packages/daphne/http_protocol.py", line 199, in serverResponse
    "path": self.path.decode("ascii"),
exceptions.UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1: ordinal not in range(128)
```

**Comment by andrewgodwin** [comment]
Weird that curl entirely ignores the HTTP spec and doesn't encode that character - handy though. Fixed in master, going to make sure things check out and release momentarily.

I couldn't get the process to crash myself when reproducing this - just the request thread serving the client died, and Twisted recovered - but I've added extra hardening anyway for any future issues.

**Comment by andrewgodwin** [comment]
Released in `0.12.1`.

**Comment by darklow** [comment]
The curl was just as example I was able to recplicate, I received these requests from some hackish bots and you can expect lot of bad and non-standard things incoming from them.
Process didn't crash, but just hanged for me, did you tried reloading page after curl-ing?
Anyway, I just tried and fix works great, now it shows `"GET /" 400 430`. 
Thank you.

**Comment by andrewgodwin** [comment]
Yeah, I understand that bad bots are the problem - I was just surprised curl let you send unicode!

I did refresh the page and still had it working for WS and HTTP, but I'm running Python 3, so maybe that's a difference? Anyway, glad to hear it's fixed.

**Comment by darklow** [comment]
Yep, I guess python 3 has no more unicode problems.
I was running 2.7.10
