### ISSUE TITLE
Cannot use unix sockets

### ISSUE THREAD

**Issue by mheppner** [andrewgodwin/daphne#8]
When launching daphne 0.11.3 with `--unix-socket=/tmp/daphne.sock`, I get an error. TCP works great though.

```
016-05-03 20:12:14,143 INFO     Starting server at /tmp/daphne.sock, channel layer app.asgi:channel_layer
Unhandled Error
Traceback (most recent call last):
  File "/app/lib/python2.7/site-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/app/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/app/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/app/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/app/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/app/lib/python2.7/site-packages/twisted/internet/unix.py", line 189, in doRead
    return self._dataReceived(data)
  File "/app/lib/python2.7/site-packages/twisted/internet/tcp.py", line 215, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/app/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)
  File "/app/lib/python2.7/site-packages/twisted/web/http.py", line 1688, in lineReceived
    self.allContentReceived()
  File "/app/lib/python2.7/site-packages/twisted/web/http.py", line 1767, in allContentReceived
    req.requestReceived(command, path, version)
  File "/app/lib/python2.7/site-packages/twisted/web/http.py", line 768, in requestReceived
    self.process()
  File "/app/lib/python2.7/site-packages/daphne/http_protocol.py", line 117, in process
    "client": [self.client.host, self.client.port],
exceptions.AttributeError: 'UNIXAddress' object has no attribute 'host'
```

**Comment by andrewgodwin** [comment]
Fixed and released in version 0.11.4.
